name: mvp1
description: A new flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Buffalo
      fonts:
        - asset: assets/fonts/BuffaloScript-Regular.otf
    - family: OhNow
      fonts:
        - asset: assets/fonts/OhNow-rBlB.otf
    - family: Exodus
      fonts:
        - asset: assets/fonts/ExodusDemo-Shino.otf
    - family: Shink
      fonts:
        - asset: assets/fonts/Shink.otf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/dancing_script/DancingScript-Regular.ttf
        - asset: assets/fonts/dancing_script/DancingScript-Bold.ttf
          weight: 700
    - family: Tweaky
      fonts:
        - asset: assets/fonts/tweaky-400.ttf
    - family: HelloParis
      fonts:
        - asset: assets/fonts/Hello_Paris.ttf
    - family: Oceania
      fonts:
        - asset: assets/fonts/Oceania-13LL.ttf
    - family: Carrinady
      fonts:
        - asset: assets/fonts/Carrinady_Thin.otf
    - family: Honey
      fonts:
        - asset: assets/fonts/honeycomb/Honeycomb-Sharp-Swash.otf
    - family: Plento
      fonts:
        - asset: assets/fonts/PLENTO-Regular.ttf
    - family: Artypa
      fonts:
        - asset: assets/fonts/Artypa_family/Artypa-Regular.otf
    - family: Acmedia
      fonts:
        - asset: assets/fonts/Acmedia.ttf
    - family: Nordic
      fonts:
        - asset: assets/fonts/Nordic_Alternative_Regular.ttf
    - family: Sherilyn
      fonts:
        - asset: assets/fonts/Sherilyn_Script.otf
    - family: Hague
      fonts:
        - asset: assets/fonts/TheHague-3zZP8.otf
    - family: Amostely
      fonts:
        - asset: assets/fonts/AmostelySignature.ttf
    - family: LotusEater
      fonts:
        - asset: assets/fonts/LotusEater_Personal_use.otf
    - family: Sarahfadhilla
      fonts:
        - asset: assets/fonts/sarahfadhilla-free.ttf
    - family: Melete
      fonts:
        - asset: assets/fonts/Melete-Regular.otf
    - family: Mustopha
      fonts:
        - asset: assets/fonts/MustophaRegular-0W759.otf
    - family: Quefira
      fonts:
        - asset: assets/fonts/Quefira.otf
    - family: Cordless
      fonts:
        - asset: assets/fonts/Cordless-DemoVersion.otf
    - family: MaronBarista
      fonts:
        - asset: assets/fonts/maronbaristapersonaluseonly-ezgxo.otf
    - family: Basmala
      fonts:
        - asset: assets/fonts/Basmala.ttf
    - family: Numbrs
      fonts:
        - asset: assets/fonts/numbrs-Regular.otf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.mvp1
    iosBundleIdentifier: com.example.mvp1
